site_name: Grupo 5
site_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05

repo_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2025.1-Grupo05

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top


nav:
  - Início : index.md
  - Atas :
    - Ata 1: atas/ata1.md
    - Ata 2: atas/ata2.md
  - Apresentações :
    - Apresentação 1 - 15/04/2025: aps/ap1.md
  - Pré-rastreabilidade :
    - Rich Ricture: prerastreabilidade/rich-picture.md
 
