site_name: IBGE
site_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05

repo_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05
repo_name: 2025.1-IBGE

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2025.1-Grupo05

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/weather-night
        name: Modo escuro

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  language: pt-BR
  favicon: assets/logo_ibge.png
  logo: assets/logo_ibge.png

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/style.css

nav:
  - Início : index.md
  - Atas :
    - Ata 1: atas/ata1.md
    - Ata 2: atas/ata2.md
  - Apresentações :
    - Apresentação 1 - 15/04/2025: aps/ap1.md
  - Planejamento : 
    - Aplicativo Escolhido: Planejamento/AplicativoEscolhido.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Cronograma: Planejamento/Cronograma.md
  - Pré-rastreabilidade :
    - Rich Ricture: prerastreabilidade/rich-picture.md
 
