site_name: IBGE
site_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05

repo_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05
repo_name: 2025.1-IBGE

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2025.1-Grupo05

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

    # Palette toggle for high-contrast
    - media: "(prefers-color-scheme: high-contrast)"
      scheme: high-contrast
      toggle:
        icon: material/brightness-1
        name: Switch to system preference

  language: pt-BR
  favicon: assets/logo_ibge.png
  logo: assets/logo_ibge.png

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Início : index.md
  - Atas :
    - Ata 1: atas/ata1.md
    - Ata 2: atas/ata2.md
    - Ata 3: atas/ata3.md
  - Apresentações:
    - 1ª Entrega: 
      - Apresentação - 1ª entrega: aps/ap1/ap1.md
      - Lista de Verificação - 1ª entrega: aps/ap1/lv1.md
  - Planejamento : 
    - Aplicativo Escolhido: Planejamento/AplicativoEscolhido.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologia.md
    - Cronograma: Planejamento/Cronograma.md
  - Pré-rastreabilidade :
    - Rich Ricture:
      - Aplicativos analisados: prerastreabilidade/rich-pic_alt.md
      - Aplicativo selecionado: prerastreabilidade/rich-picture.md
  - Verificação : 
    - Entrega 1:
      - Grupo +1: Verificacao/entrega1/etr1_gr+1.md
 